### ISSUE TITLE
Installation failed [Fixed]

### ISSUE THREAD

**Issue by moryoav** [Bee-Mar/mmpm#1]
Installation initially failed because I had libgit2 missing (pip3 install pygit2 failed).
Additionally, "sudo apt-get install libgit2-dev" succeeded but pip3 install pygit2 complained that it can't find the right version.
My solution was:

```
$ wget https://github.com/libgit2/libgit2/archive/v0.28.1.tar.gz
$ tar xzf v0.28.1.tar.gz
$ cd libgit2-0.28.1/
$ cmake .
$ make
$ sudo make install
```

and then:

```
sudo pip3 install pygit2
sudo ldconfig 
python3 -c 'import pygit2'
```

Only then could I proceed with the installation of mmpm.

**Comment by Bee-Mar** [comment]
Thanks for letting me know! I'll add this to the installation instructions. I must have installed something previously was bundled `libgit2-dev`, and never realized it was a dependency of `pygit2`.

**Comment by Bee-Mar** [comment]
I've updated the README, so I'll close this issue now.

**Comment by drippyer** [comment]
I am actually still having an issue because of pygit2. Attempting to run any mmpm command results in
`PyGit2 package not found. Pip installing with --user flag.`
That eventually fails with 
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1t_8046a/pygit2/`

**Comment by Bee-Mar** [comment]
Have you tried any of the following

```sh
python -m pip install --upgrade pip

python3 -m pip3 install --upgrade pip3

pip install --upgrade setuptools

pip install ez_setup

easy_install distribute

pip install --upgrade distribute

sudo apt install python-dev libpython-dev libevent-dev python3-dev libpython3-dev  -y

```

**Comment by drippyer** [comment]
I think it was upgrading pip that fixed it? I'd already tried upgrading setuptools and that didn't help but I can at least list installed modules now!

**Comment by Bee-Mar** [comment]
Awesome! I actually just went in and removed the code that used pygit2, which was just one line. I swore I used it elsewhere, but that was probably in some previous version. I'm about to push the new version that doesn't need the `pygit2` module.
